name: Build and Compile Check

on:
  pull_request:
    branches: [ master, main, develop ]
  push:
    branches: [ master, main, develop ]

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        config: [Debug, Release]
        platform: [x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore HEW_2025.sln

    - name: Build solution
      run: msbuild HEW_2025.sln /p:Configuration=${{ matrix.config }} /p:Platform=${{ matrix.platform }} /m

    - name: Check for build errors
      if: failure()
      run: |
        echo "Build failed for config=${{ matrix.config }}, platform=${{ matrix.platform }}"
        exit 1

    - name: Collect build outputs (Release/master|main only)
      if: (startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/main')) && matrix.config == 'Release'
      shell: powershell
      run: |
        # cleanup
        if (Test-Path artifact) { Remove-Item artifact -Recurse -Force }
        New-Item -ItemType Directory -Path artifact | Out-Null

        # Collect common native outputs (exe, dll, pdb) from all projects
        Get-ChildItem -Path . -Include *.exe,*.dll,*.pdb -Recurse -ErrorAction SilentlyContinue |
          ForEach-Object {
            Copy-Item -Path $_.FullName -Destination (Join-Path $PWD 'artifact') -Force
          }

        # If there are additional folders (e.g., x64\Release), also copy them if present
        if (Test-Path ".\x64\Release") {
          Copy-Item -Path ".\x64\Release\*" -Destination "artifact" -Recurse -Force
        }

        # Copy Assets from HEW_2025/Assets if exists
        if (Test-Path ".\HEW_2025\Assets") {
          New-Item -ItemType Directory -Path artifact\Assets -Force | Out-Null
          Copy-Item -Path ".\HEW_2025\Assets\*" -Destination "artifact\Assets" -Recurse -Force
        }

    - name: Upload artifact (optional)
      if: (startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/main')) && matrix.config == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: HEW_2025-${{ matrix.platform }}-${{ matrix.config }}-${{ github.run_number }}
        path: artifact/**
        compression-level: 9

    - name: Archive build for release
      if: (startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/main')) && matrix.config == 'Release'
      shell: powershell
      run: |
        Compress-Archive -Path artifact\* -DestinationPath HEW_2025.zip -Force

    - name: Install GitHub CLI
      if: (startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/main')) && matrix.config == 'Release'
      shell: powershell
      run: |
        choco install gh -y
        gh --version

    - name: Create release on public repo and upload asset
      if: (startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/main')) && matrix.config == 'Release'
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.PUBLIC_RELEASE_PAT }}
      run: |
        set -e
        TARGET_REPO="aptma-sHEWTeam/hew-game-release"
        TAG="v0.1.${{ github.run_number }}"
        TITLE="Auto build ${{ github.run_number }}"

        gh release delete "$TAG" --repo "$TARGET_REPO" --yes 2>/dev/null || true

        gh release create "$TAG" "HEW_2025.zip" \
          --repo "$TARGET_REPO" \
          --title "$TITLE" \
          --notes "Automated build from private repo run #${{ github.run_number }}" \
          --prerelease

  compile-check:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Compile check (Debug/x64)
      run: msbuild HEW_2025.sln /p:Configuration=Debug /p:Platform=x64 /m /v:quiet
      continue-on-error: false